version: '3.4'

services:
    go-2:
        image: gitlab.codixfr.private:5005/enterpriseapps/images/go-api:latest
        ports:
            - ${API_PORT:-4000}:${APP_PORT:-4000}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
        environment:
            - BRANCH=${BRANCH}
        restart: always
