version: '3.4'

services:
    go:
        image: gitlab.codixfr.private:5005/enterpriseapps/images/go-api:latest
        ports:
            - 4000:4000
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
        environment:
            - BRANCH=${BRANCH}
